# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'StreamerAPP' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Fabric'
  pod 'TwitterKit'
  pod 'TwitterCore'  # Pods for StreamerAPP

  target 'StreamerAPPTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'StreamerAPPUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
